# Micromamba environment file
# https://marketplace.visualstudio.com/items?itemName=corker.vscode-micromamba

name: flaml

channels:
  - conda-forge

dependencies:
  - jupyter-packaging
  - jupyterlab
  - jupyter
  - nodejs
  - pytest
  - pytest-check-links
  - python
  - yarn
  - pandas
  - numpy
  - scikit-learn
  - scipy
  - pip
  - seaborn
  - pip:
    - "flaml[automl]"
    - shap
    - tqdm
    - stopit