# extract the lambda function from the dictionary:
# example dictionary
# ['lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: Add(AR, DU)',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: AQ(CR, Sub(CS, CF))',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: Sub(AM, FL)',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: Mul(DU, Sub(-1, EL))',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: Sub(-1, DU)',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: Sub(FD , Mul(0, BC))',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: Add(DA, Mul(FL, AX))',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: Add(AQ(BQ, EL), CL)',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: AQ(FE, CW )',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: AQ(EH, CS)',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: Sub(AQ(FD , GB), Sub(DH, DH))',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: Sub(DF, DE)',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: Sub(AF, BC)',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: AQ(Sub(DN, BC), Mul(GF, DA))',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: AQ(BZ, BR)',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: Add(GL, GL)',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: AQ(DH, CH)',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: Add(Add(EP, EU), DN)',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: AQ(DF, FL)',
 'lambda AB,AF,AH,AM,AR,AX,AY,AZ,BC,BD ,BN,BP,BQ,BR,BZ,CB,CC,CD ,CF,CH,CL,CR,CS,CU,CW ,DA,DE,DF,DH,DI,DL,DN,DU,DV,DY,EB,EE,EG,EH,EL,EP,EU,FC,FD ,FE,FI,FL,FR,FS,GB,GE,GF,GH,GI,GL: Sub(AB, CB)',



def extract_lambda_function(dict):